(function() {
  var $, alphacoders_api, alphacoders_api_auth_key, api_url, username;

  $ = jQuery;

  username = "hit9";

  api_url = "https://api.github.com/users/";

  alphacoders_api_auth_key = "30cdde245ca734f3a637b1ad22419b90";

  alphacoders_api = "http://wall.alphacoders.com/api1.0/get.php?auth=" + alphacoders_api_auth_key + "&sort=newest";

  $.getJSON(alphacoders_api, function(res) {
    return alert(res.url);
  });

  $.getJSON(api_url + username, function(res) {
    var avatar_url;
    document.title = res.login + "'s Resume";
    avatar_url = "https://secure.gravatar.com/avatar/" + res.gravatar_id + "?size=170";
    $("#avatar").attr("src", avatar_url);
    $("#name").text(res.name);
    $("#user-info #location").append(res.location);
    $("#user-info #email").append(res.email);
    $("#user-info #company").append(res.company);
    $("#user-info #blog").append("<a href=\"" + res.blog + "\" >" + res.blog + "</a>");
    return $("#followers #follower-number").text(res.followers);
  });

  $.getJSON(api_url + username + "/repos?type=owner", function(res) {
    var homepage, repo, _i, _len, _ref, _results;
    res.sort(function(a, b) {
      return b.watchers_count - a.watchers_count;
    });
    _ref = res.slice(0, 5);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      repo = _ref[_i];
      homepage = "";
      if (repo.homepage) {
        homepage = "<a href=\"" + repo.homepage + "\" ><i class=\"icon-home icon-white\" ></i></a>";
      }
      _results.push($("#repolist").append("        <li style=\"display: list-item;\">          <ul class=\"repo-stats\">            <li class=\"stars\">              <i class=\"icon-star icon-white\"></i>" + repo.watchers_count + "            </li>            <li class=\"forks\">              <i class=\"icon-share-alt icon-white\"></i>              " + repo.forks_count + "            </li>            <li class=\"created_time\">              <i class=\"icon-time icon-white\"></i>" + repo.created_at.substring(0, 10) + "            </li>          </ul>          <h3>            <a href=\"https://github.com/" + username + "/" + repo.name + "\">            " + repo.name + "            </a>          </h3>          <p id=\"description\">" + homepage + "&nbsp; " + repo.description + "</p>        </li>      "));
    }
    return _results;
  });

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
