(function() {
  var user;

  user = new Gh3.User("hit9");

  $(document).ready(function() {
    return user.fetch(function(err, res) {
      var avatar_url;
      document.title = res.login + "'s Resume";
      avatar_url = "https://secure.gravatar.com/avatar/" + res.gravatar_id + "?size=170";
      $("#avatar").attr("src", avatar_url);
      $("#name").text(res.name);
      $("#user-info #location").text(res.location);
      $("#user-info #email").text(res.email);
      $("#user-info #company").text(res.company);
      return $("#user-info #blog").text(res.blog);
    });
  });

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
